# Generated by Django 2.2.4 on 2022-09-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
    ]
